---
name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  test-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/actions/setup-env

      - name: Prepare
        run: make prepare-env

      - name: Tests
        run: make tests

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: output/*.xml
