---
name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  test-ansible-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: requirements
        run: pip3 install -r requirements.txt

      - name: prepare
        run: make prepare-env  tests