---
name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  test-anbile-playbook:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: test
        run: make prepare unit
